/**
 * @author © ColdByDefault
 * @license Copyright (c) 2026 ColdByDefault. All rights reserved.
 * @version 6.x.x
 */

import type { Metadata } from "next";
import { getLocale } from "next-intl/server";
import { generateMediaSectionSEO } from "@/lib/configs/seo";
import { Separator } from "@/components/ui/separator";
import {
  ArchitectureDiagram,
  TechStackGrid,
  WorkflowDiagram,
  CodeExamples,
  PerformanceMetrics,
} from "@/components/aboutPortoPage";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ExternalLink, FileText, Info } from "lucide-react";

export async function generateMetadata(): Promise<Metadata> {
  const locale = await getLocale();

  return generateMediaSectionSEO("aboutPortfolio", locale);
}

export default function PortfolioDocumentation() {
  return (
    <div className="min-h-screen">
      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-6 py-12">
        {/* Hero Section */}
        <div className="text-center mb-16">
          <h1 className="text-5xl font-bold mb-6 text-balance">
            ColdByDefault Portfolio
            <span className="block text-primary">Technical Documentation</span>
          </h1>
          <p className="text-xl text-muted-foreground mb-8 max-w-3xl mx-auto text-pretty">
            Technical documentation for the production Next.js 16 portfolio,
            covering architecture, stack choices, API surface, security
            hardening, and quality workflows aligned with the current README.
          </p>
        </div>

        {/* Technical Documentation Notice */}
        <div className="mb-16">
          <Card className="border-amber-200 bg-amber-50 dark:border-amber-800 dark:bg-amber-950/20">
            <CardContent className="pt-6">
              <div className="flex items-start gap-3">
                <Info className="w-5 h-5 text-amber-600 dark:text-amber-400 mt-0.5 shrink-0" />
                <div className="text-sm">
                  <p className="font-medium text-amber-800 dark:text-amber-200 mb-1">
                    Technical Documentation Language Notice
                  </p>
                  <p className="text-amber-700 dark:text-amber-300">
                    This technical documentation is available in English only.
                    Any translations you see are automatically generated by your
                    browser and may not accurately represent technical concepts
                    and implementation details.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* System Architecture */}
        <section className="mb-20">
          <div className="text-center mb-12 w-full">
            <h2 className="text-3xl font-bold mb-4 text-center">
              System Architecture & Design
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Explore the edge-first architecture behind this portfolio,
              including App Router route groups, proxy-based locale handling,
              API boundaries, and shared security layers.
            </p>
          </div>
          <ArchitectureDiagram />
        </section>

        <Separator className="my-20" />

        {/* Technical Stack */}
        <section className="mb-20">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-4">
              Technical Stack & Expertise
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Current production stack across frontend, backend, AI surfaces,
              database, and localization: Next.js 16, React 19, TypeScript,
              Prisma, Neon, and next-intl.
            </p>
          </div>
          <TechStackGrid />
        </section>

        <Separator className="my-20" />

        {/* Development Workflow */}
        <section className="mb-20">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-4">
              Development Workflow & Methodology
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              End-to-end delivery workflow from planning and strict TypeScript
              development to linting, Playwright accessibility checks, and
              deployment automation.
            </p>
          </div>
          <WorkflowDiagram />
        </section>

        <Separator className="my-20" />

        {/* Code Examples */}
        <section className="mb-20">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-4">
              Code Examples & Implementation
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Real-world code samples reflecting production patterns used across
              this codebase, including auth/session validation, typed APIs, and
              maintainable component structure.
            </p>
          </div>
          <CodeExamples />
        </section>

        <Separator className="my-20" />

        {/* Performance & Quality */}
        <section className="mb-20">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-4">
              Performance & Quality Assurance
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Practical quality and reliability metrics spanning Lighthouse,
              accessibility, security headers, and build/runtime optimization.
            </p>
          </div>
          <PerformanceMetrics />
        </section>
        <section
          className="text-center"
          aria-labelledby="documentation-section"
        >
          <Card
            className="border-primary/20"
            role="region"
            aria-labelledby="documentation-card-title"
          >
            <CardHeader>
              <CardTitle
                id="documentation-card-title"
                className="flex items-center gap-2 justify-center"
              >
                <FileText className="h-5 w-5" aria-hidden="true" />
                Technical Documentation
                <Badge
                  variant="default"
                  className="bg-green-500"
                  aria-label="Documentation status: Online"
                >
                  Online
                </Badge>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="mb-4">
                Full API and component documentation with implementation
                references.
              </p>
              <Button asChild variant="outline">
                <Link
                  href="https://docs.coldbydefault.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label="View comprehensive technical documentation (opens in new tab)"
                >
                  <ExternalLink className="mr-2 h-4 w-4" aria-hidden="true" />
                  View Documentation
                </Link>
              </Button>
            </CardContent>
          </Card>
        </section>
      </main>
    </div>
  );
}
